overrides:
  ceph:
    log-whitelist:
    - reached quota
    - wrongly marked me down
tasks:
- install:
    rhbuild : 1.3.0
- ceph:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

